### ISSUE TITLE
PNG files detected as executables

### ISSUE THREAD

**Issue by raphaelMrci** [Saverio976/NorMatrix#11]
**The bug**
When NorMatrix check if executable is created, its detect *.png files as executables files.

**To Reproduce**
1. Place a png file on a folder
2. Launch NorMatrix on it.

**Expected behavior**
Maybe just ignore PNG files ? I don't know if png are able to cause issues for Marvin, maybe just check if its name is on snake_case

**Desktop:**
-   OS: GNU/LINUX - Pop!_OS
-   Version \[21.10\]

**Comment by Saverio976** [comment]
if you check the permissions for your png, you will see that it has executable permission (`ls -l yourpng.png`)
i check all file that have the executable permission
