### ISSUE TITLE
detect operator in strings

### ISSUE THREAD

**Issue by Vivelis** [Saverio976/NorMatrix#13]
**Describe the bug**
Normatrix detect operator like '/' in strings declaration.

**To Reproduce**
```c
static const char str_help[] = "USAGE\n./asm file_name[.s]\n
```
get :
```
sources/main.c:26: bad space for operator: /
 -> nope: sources/main.c (2)
```
**Expected behavior**
should detect nothing

**Desktop:**
-   OS: Linux Mint 20.3 Cinnamon
-   Version 5.2.7

**Comment by Saverio976** [comment]
a way arout could be to split your string like this:

static const char str_help[] = "USAGE\n./asm file_name[.s]\n" \
                                               "rest of the string";
