### ISSUE TITLE
don't support 2 size array

### ISSUE THREAD

**Issue by Vivelis** [Saverio976/NorMatrix#3]
When see "char **str'' -> "bad space for operator: * "

**To Reproduce**
* create a two size array with "**"

**Expected behavior**
It should not stop on this issue.

**Desktop (please complete the following information):**
-   OS: Linux Mint 20.3 Cinnamon
-   Version: 5.2.7

**Additional context**
Used in github action.

**Comment by Saverio976** [comment]
thanks, just figured out with the v0.2.1
