### ISSUE TITLE
get negative 0 result

### ISSUE THREAD

**Issue by Vivelis** [Saverio976/NorMatrix#5]
**Describe the bug**
the result for 0 is "-0"
![hmmm](https://user-images.githubusercontent.com/42516894/155005625-1f6f3989-4e7b-4b64-8977-acffc0069c4c.png)

**To Reproduce**
have no error

**Expected behavior**
result is "0" and not "-0"

**Desktop (please complete the following information):**
-   OS: linux mint

**Additional context**
vs code terminal

**Comment by Saverio976** [comment]
this is intended, because the result of this stats are the pseudo note that will be subtract to the true result of your project.
but if you have no coding style error, 0 will be subtract (so -0)
