### ISSUE TITLE
normatrix don't like too long header

### ISSUE THREAD

**Issue by Vivelis** [Saverio976/NorMatrix#6]
**Describe the bug**
detect an error when header have more than one line of description.
![normatrix don't like header](https://user-images.githubusercontent.com/42516894/155006743-39442010-6a32-4241-b3b8-53c297907690.png)

**To Reproduce**
have a header with a two line description. or a header that is 7 line len.

**Expected behavior**
don't detect an error

**Desktop (please complete the following information):**
-   OS: linux mint

**Additional context**
vs code

**Comment by Saverio976** [comment]
yes, normatrix check if the string is very equal to the header with 5 line
I don't know if it can be a coding style error to have an header with 2 line or more comments

**Comment by Saverio976** [comment]
Fix with latest push
