### ISSUE TITLE
NorMatrix don't like backslash

### ISSUE THREAD

**Issue by Vivelis** [Saverio976/NorMatrix#7]
**Describe the bug**
Return error when use '\' in c scripts.

**Screen**
![normatrix_don't_like_backslash](https://user-images.githubusercontent.com/42516894/155343756-c16139ec-1a18-4b86-9556-0cf4019b1725.png)

**To Reproduce**
Use '\' to go to the next line => give "maybe too many branch ?" and give "two spaces alone" for the first occurrence.
![normatrix_error_exemple](https://user-images.githubusercontent.com/42516894/155344073-ca5eb1eb-ca1e-4fec-947f-15e43b2cb95c.png)

**Expected behavior**
No error or an info.

**Desktop (please complete the following information):**
-   OS: Linux mint

**Additional context**
used with a my_putstr() to have a larger text.

**Comment by Saverio976** [comment]
I will try to implement that ASAP

**Comment by Saverio976** [comment]
Fix with latest commit
